### ISSUE TITLE
Endgame bug - player has no territories but is invited to place reinforcements

### ISSUE THREAD

**Issue by olyis** [markbutler94/risk#11]
The following exception was witnessed at the end of a game. Looks like the `random.sample(ownedTerritories, 1)` call was problematic, which is only possible if `ownedTerritories` is empty. Doesn't usually happen, so it's a nondeterministic bug, somehow.

Seems that either ai_basic is calculating `ownedTerritories` wrong, or the game shouldn't have invited it to place reinforcements.

I didn't think to grab the game log before rerunning so can't take a look at that unfortunately.

> ('Move:', '18')
Traceback (most recent call last):
  File "risk.py", line 378, in <module>
    t = aiCall(p, "placeReinforcements") # Should probably check that this string is acceptable?
  File "risk.py", line 59, in aiCall
    return getattr(globals()[players[player].ai],request)(player)
  File "c:\src\risk\ai_basic.py", line 46, in placeReinforcements
    return random.sample(ownedTerritories,1)[0]
  File "C:\Python27\lib\random.py", line 323, in sample
    raise ValueError("sample larger than population")
ValueError: sample larger than population

**Comment by markbutler94** [comment]
I'll have a look - will be much easier to catch with the moves.log so I'll grab that if I encounter the bug!

**Comment by markbutler94** [comment]
In fact I've just encountered a similar one:

> Traceback (most recent call last):
>   File "risk.py", line 377, in <module>
>     t = aiCall(p, "placeReinforcements") # Should probably check that this strin
> g is acceptable?
>   File "risk.py", line 58, in aiCall
>     return getattr(globals()[players[player].ai],request)(player)
>   File "C:\GIT\risk\ai_improved.py", line 78, in placeReinforcements
>     return random.sample(list(ownedTerritories),1)[0]
>   File "C:\Users\MarkButler\AppData\Local\Programs\Python\Python36-32\lib\random
> .py", line 318, in sample
>     raise ValueError("Sample larger than population or is negative")
> ValueError: Sample larger than population or is negative

The log file is here, I'll investigate
[moves.log](https://github.com/markbutler94/risk/files/1572005/moves.log)
